version: '3.8'

services:
  create-client-service:
    image: c22c5320fec3
    container_name: create-product-service
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=mysql-christopherobin.alwaysdata.net
      - DB_USER=358042_admin
      - DB_PASSWORD=YqUZn6T6AxLYc5k
      - DB_NAME=christopherobin_minimarket
    networks:
      - clientefeliz-network

  list-client-service:
    image: 9626aa8b1cf2
    container_name: list-product-service
    ports:
      - "8086:8086"
    environment:
      - DB_HOST=mysql-christopherobin.alwaysdata.net
      - DB_USER=358042_admin
      - DB_PASSWORD=YqUZn6T6AxLYc5k
      - DB_NAME=christopherobin_minimarket
    networks:
      - clientefeliz-network

  update-client-service:
    image: ca36af4e3456
    container_name: update-product-service
    ports:
      - "8087:8087"
    environment:
      - DB_HOST=mysql-christopherobin.alwaysdata.net
      - DB_USER=358042_admin
      - DB_PASSWORD=YqUZn6T6AxLYc5k
      - DB_NAME=christopherobin_minimarket
    networks:
      - clientefeliz-network

  clientefeliz-frontend:
    image: feb81c736131
    container_name: minimarket-frontend
    ports:
      - "3002:3002"
    networks:
      - clientefeliz-network

networks:
  clientefeliz-network:
    driver: bridge